url: "https://hakiimj.github.io"
baseurl: ""
title: Hakiim Jamaluddin
email: ahmadhakiim@upm.edu.my
description: Senior Lecturer in Statistics & Data Science
lang: en
first_name: Hakiim
last_name: Jamaluddin
footer_text: >
  Senior Lecturer in Statistics & Data Science. UPM & UNSW Alumni.
github_username: HakiimJ
linkedin_username: hakiim-j
x_username: hakiimj_
google_scholar_id: F8M1UL8AAAAJ
orcid_id: 0000-0002-1715-6912
research_gate_profile: Ahmad-Hakiim-Jamaluddin
theme: system
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:title/
paginate: 10
paginate_path: /blog/page:num/
timezone: Asia/Kuala_Lumpur
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-email-protect
  - jekyll-twitter-plugin
  - jemoji
exclude:
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - package-lock.json
  - Rakefile
  - CHANGELOG.md
  - LICENSE
  - README.md
  - .gitignore
  - .github
  - .git
news_limit: 5
latest_papers_limit: 3
related_blog_posts:
  enabled: true
  max_related: 3
